spring.application.name=discovery-service
server.port=8761

# Désactiver la découverte automatique des services liés (pour éviter les boucles)
eureka.client.register-with-eureka = false
eureka.client.fetch-registry = false

# Configurer le port du client (le port sur lequel il s'attend à être joint)
eureka.instance.port = 8761
